name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NPM version'
        required: true
        default: 'patch' # Default version if not provided

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Configure Git identity
        run: |
          git config --global user.email "madeluhung@gmail.com"
          git config --global user.name "Made Luhung"

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Print Masked Secret
        run: echo "Secret Value: ${{ secrets.NPM_AUTH_TOKEN }}"

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
